---

- name: Debian | set automysqlbackup_loaded_os_family
  set_fact: 
    automysqlbackup_loaded_os_family: "{{ ansible_os_family  }}"
  tags:
    - automysqlbackup

- name: Debian | run apt update
  sudo: yes
  apt: update_cache=yes
  tags:
    - automysqlbackup

- name: Debian | run apt upgrade (security)
  sudo: yes
  apt: upgrade=safe
  tags:
    - automysqlbackup

- name: Debian | install automysqlbackup
  sudo: yes
  apt: pkg=automysqlbackup state=latest
  tags:
    - automysqlbackup
