---

- include: debian.yml
  when: ansible_os_family == 'Debian' or ansible_distribution == 'Ubuntu'

- include: redhat.yml
  when: ansible_os_family == 'RedHat' or ansible_distribution == 'CentOS'

- include: default.yml
  when: automysqlbackup_loaded_os_family|default(False) == False

- name: apply automysqlbackup configuration
  sudo: yes
  template:
    src: automysqlbackup.j2
    dest: /etc/default/automysqlbackup
    group: root
    owner: root
    mode: 0600
  tags:
    - automysqlbackup

- name: add automysqlbackup cron job
  sudo: yes
  cron:
    name: "automysqlbackup"
    minute: "{{ automysqlbackup_cron.minute }}"
    hour: "{{ automysqlbackup_cron.hour }}"
    day: "{{ automysqlbackup_cron.day }}"
    month: "{{ automysqlbackup_cron.month }}"
    weekday: "{{ automysqlbackup_cron.weekday }}"
    user: root
    job: "/usr/sbin/automysqlbackup"
  tags:
    - automysqlbackup
